# Feel free to disable non-critical HA parts during devel by commenting lines out
# Generated in hadk by executing: rpm/dhd/helpers/add_new_device.sh

Description: Pattern with UI related packages for c8813q configurations
Name: jolla-ui-configuration-c8813q
Requires:
- jolla-ambient-z@ICON_RES@
- ambient-icons-closed-z@ICON_RES@
Summary: Jolla UI Configuration c8813q

